{
   "providerName":"Framework Television",
   "lastUpdated":"2020-01-24T10:58:21-05:00",
   "language":"en",
   "movies":[
      {
         "id":"333004416",
         "title":"Javascript Tip Calculator",
         "shortDescription":"Never do restaurant panic-math again.  This tip calculator app will calculate your tip every time. This is a great first app for new developers.  Use HTML5, JavaScript, and the Onsen UI library to build this simple application.",
         "thumbnail":"https://i.vimeocdn.com/video/778868116_800x450.png",
         "releaseDate":"2019-04-28T19:11:02-04:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "new",
            "coding",
            "coding_projects"
         ],
         "content":{
            "dateAdded":"2019-11-08T12:17:49-05:00",
            "duration":1484,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/333004416.hd.mp4?s=3a69f50006eefb5d6b348a2e11a6e9cfbddc0ffc\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1199215
               }
            ]
         }
      },
      {
         "id":"333004214",
         "title":"Finger Paint App with HTML5 Canvas",
         "shortDescription":"Put on your smock for this HTML5 Canvas Paint tutorial.  Create an HTML5 canvas paint App in this tutorial with Mark Lassoff.  You'll learn how to place the HTML5 canvas in your HTML code, the JavaScript you need to do HTML5 canvas drawing, and the necessary events to allow the user to finger paint on the HTML5 canvas.",
         "thumbnail":"https://i.vimeocdn.com/video/778868286_800x450.png",
         "releaseDate":"2019-04-28T19:08:52-04:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "coding",
            "coding_projects"
         ],
         "content":{
            "dateAdded":"2019-11-08T12:17:49-05:00",
            "duration":1336,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/333004214.hd.mp4?s=fdf526141dbd19ae70c394ecb8b1a8ceeb06a94b\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1224078
               }
            ]
         }
      },
      {
         "id":"336431081",
         "title":"Make a Digital Clock... with a Twist",
         "shortDescription":"In this video, you'll create a digital clock using JavaScript and the Date() object.  We'll also display local news headlines from an API using Fetch().",
         "thumbnail":"https://i.vimeocdn.com/video/783272809_800x450.png",
         "releaseDate":"2019-05-15T15:43:52-04:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "coding",
            "coding_projects"
         ],
         "content":{
            "dateAdded":"2019-11-08T12:17:49-05:00",
            "duration":1480,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/336431081.hd.mp4?s=8ad40b2f9a6fe006d8525f2294024e12fa46bdf6\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1754728
               }
            ]
         }
      },
      {
         "id":"333004660",
         "title":"Weather Conditions App",
         "shortDescription":"Do you need to bring a jacket?  Create this weather conditions app and see the weather in any city on the face of the globe.  This app uses HTML5, JavaScript, the OnsenUI library and Open WeatherMap API.",
         "thumbnail":"https://i.vimeocdn.com/video/778867914_800x450.png",
         "releaseDate":"2019-04-28T19:13:39-04:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "coding",
            "coding_projects"
         ],
         "content":{
            "dateAdded":"2019-11-08T12:17:49-05:00",
            "duration":1798,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/333004660.hd.mp4?s=1e1e5529ae614f537cf60098c59a5630dcd4cb5d\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1209750
               }
            ]
         }
      },
      {
         "id":"333003869",
         "title":"Make a Beer Pairing App",
         "shortDescription":"Which beer goes with pizza?  Red? White? A Nice Merlot? Make a Javascript app that uses an API to get data which you will display to the user.  This app will help you pair a beer with your food.\n\nIn this video, Mark will create a JavaScript app that will query the Punk API and display information about beers in its database.  You'll learn to make a JavaScript application as you're invited to code along with this video.",
         "thumbnail":"https://i.vimeocdn.com/video/778866895_800x450.png",
         "releaseDate":"2019-04-28T19:05:09-04:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "new",
            "coding",
            "coding_projects"
         ],
         "content":{
            "dateAdded":"2019-11-08T12:17:49-05:00",
            "duration":1505,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/333003869.hd.mp4?s=45ab31b9df1b3c9910ad157679ee6a4de7227357\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1662269
               }
            ]
         }
      },
      {
         "id":"333004911",
         "title":"Movie Tracker",
         "shortDescription":"For the movie buff in all of us, this app lets you track movies you've seen as well as some information about those movies.  This app uses HTML5, JavaScript, the jQuery library, and localForage for storage.  Learn about client side storage as you build this app with Mark.",
         "thumbnail":"https://i.vimeocdn.com/video/778867219_800x450.png",
         "releaseDate":"2019-04-28T19:16:47-04:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "coding",
            "coding_projects"
         ],
         "content":{
            "dateAdded":"2019-11-08T12:17:49-05:00",
            "duration":1535,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/333004911.hd.mp4?s=7503c8452f33299231876249a5daceefc234d6d9\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1039782
               }
            ]
         }
      },
      {
         "id":"335405890",
         "title":"Creating an App with the Google Maps API",
         "shortDescription":"Learn how to create an app with the JavaScript API for Google Maps. This app first displays a map of the local area and then drops pins on the map where there are restaurants.  Click on a pin yields further information about each restaurant.    This application uses vanilla JavaScript and the Google Maps and Places APIs.",
         "thumbnail":"https://i.vimeocdn.com/video/781987352_800x450.png",
         "releaseDate":"2019-05-10T09:25:44-04:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "new",
            "coding",
            "coding_projects"
         ],
         "content":{
            "dateAdded":"2019-11-08T12:17:49-05:00",
            "duration":1092,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/335405890.hd.mp4?s=6b17c9bbe6bb80d8e67cb7a2e1cd9d26e9046ae1\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1450377
               }
            ]
         }
      },
      {
         "id":"370892754",
         "title":"Most Used Programming Languages 2019 | Framework Technical Report with Mark Lassoff 001",
         "shortDescription":"In this Framework Technical Report, Mark discusses the most used programming languages in 2019.  \n\nThe most used programming languages in the world include JavaScript, Java, C% and PHP.\n\nWeb Site: http://www.frameworktv.com\nFacebook: https://www.facebook.com/groups/frameworkcommunity\n\nTranscript\nOver the years dozens of programming languages have come and gone. Since the creation of the world wide web, things have stabilized a bit.  There are currently five or six languages that are used to create the apps and websites you use each day.  \n\nThe most popular of these is JavaScript. JavaScript is a two-decade-old language used to program interaction within web applications. In recent years, JavaScript has expanded to be used on web servers and mobile applications as well. Because it can be used almost everywhere JavaScript is an important language to know right now.\n\nAlso currently popular are the languages PHP, Java, and C-sharp. These languages are used on web servers to create enterprise-level software and applications like eCommerce systems, content management systems and the business end of multiplayer online games.\n\nFor Framework Technical Minute, I’m Mark Lassoff",
         "thumbnail":"https://i.vimeocdn.com/video/828248805_800x450.png",
         "releaseDate":"2019-11-04T10:00:13-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "coding"
         ],
         "content":{
            "dateAdded":"2019-11-08T12:17:49-05:00",
            "duration":58,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/370892754.hd.mp4?s=46ad30459334abc23a13d6342755abb3e7ddd415\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":3746776
               }
            ]
         }
      },
      {
         "id":"370892924",
         "title":"iOS vs Android: Which Mobile OS Is Most Popular? | Framework Technical Report 003",
         "shortDescription":"iOS vs Android: Which Mobile OS Is Most Popular? Mark discusses the user base of iOS versus the user base of Android.  The numbers worldwide versus in the US are surprising.\n\nTranscript\nIn the US, it’s a battle between Apple’s iOS operating system running on iPhones and iPads and the Android operating system running on Android devices.  Worldwide, it appears, that battle may be over and a winner has been declared.\n\nAccording to CNET, a full 85% of mobile devices globally run the Android operating system.  iOS has a 13% market share worldwide.\nThe numbers in the US tell a bit of a different story.  According to Statista, iOS holds 48% of the US market share while Android is used on 51% of phones.  Apple’s iOS operating system has been growing in the US over the last five years taking market share away from Android, and benefitting from the death of the Microsoft mobile and Blackberry Operating Systems.\n\nWorldwide Android’s lead may be insurmountable, but, the battle for mobile dominance in the United States continues with the new iPhone 11 and Google Pixel 4 making compelling arguments for both sides.\n\nFor Framework Technical Minute, I’m Mark Lassoff\n\nWeb:  http://www.frameworktv.com\nFacebook:  https://www.facebook.com/groups/frameworkcommunity/\n\n\n #android #iOS #BestSmartphone #BestPhone #BestTech",
         "thumbnail":"https://i.vimeocdn.com/video/828249214_800x450.png",
         "releaseDate":"2019-11-04T10:00:54-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "coding"
         ],
         "content":{
            "dateAdded":"2019-11-08T12:17:49-05:00",
            "duration":67,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/370892924.hd.mp4?s=baf7b490f02f1d7135b845c28477c91e90b6c847\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":3714077
               }
            ]
         }
      },
      {
         "id":"370893109",
         "title":"Coding For Kids: Where to Start | Framework Technical Report 005",
         "shortDescription":"There has been a large movement to teach coding for kids along with other critical STEM skills.  In this video Mark reports on options to learn programming for kids.\n\nTranscript\nWhat’s the right age for kids to learn to code?\n\nWhile younger kids may not have the type of abstract thinking ability that formal coding requires, there are resources for kids to get started younger and younger.\n\nKids as young as seven are using Scratch, a visual coding system, to create applications and simple games as they develop coding skills.  Minecraft, the popular terrain building games, offers coding programs supported by Microsoft that teach coding skills in-game.\n\nThere are also a number of toy robot that helps kids learn coding skills, like the Wonder Workshop Dash and Lego’s Boost Creative Tool Box Fun Robot.\n\nFor older kids, there’s everything from after-school training centers to summer camps that teach coding skills.  Code Ninjas, for example,  is teaching kids development skills from coast to coast, while the iD Tech Summer Camps will have kids coding at over 100 college campuses across the country.\n\nFor Framework Technical Minute, I’m Mark Lassoff\n\n\nWeb Site: http://www.frameworktv.com\nFacebook: https://www.facebook.com/groups/frameworkcommunity",
         "thumbnail":"https://i.vimeocdn.com/video/828248922_800x450.png",
         "releaseDate":"2019-11-04T10:01:35-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "coding"
         ],
         "content":{
            "dateAdded":"2019-11-08T12:17:49-05:00",
            "duration":61,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/370893109.hd.mp4?s=698a63b05f16b8c91106edd8610055171ed5f1cd\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":3354165
               }
            ]
         }
      },
      {
         "id":"370893009",
         "title":"The State of Online Video |  Framework Technical Report 004",
         "shortDescription":"Online video has exploded over the last decade. In this report, Mark reviews the state of online video and what to expect in the near future\n\nTranscript\nAccording to a  Cisco report, by 2021, 80% of the world’s internet traffic will be video.  That amount of traffic translates to nearly 1.9 billion internet video users and three trillion minutes of video consumed each month.\n\nYouTube alone boasts 1.3 billion users and an audience that includes 8 out of ten 18 to 49-year-olds.\n\nSuffice to say internet video is exploding.\n\nIncluded in the category of internet video are short-form videos, like those found on YouTube as well as streaming video found on Netflix or Roku.  What’s missing from the video stats?  Gaming.  Games are another exploding category closely related to video.\n\nWhat’s the next trend in online video?  Convergence.  As Youtube gets into streaming television and movies with its Youtube TV option expect to see more video sites trying to offer all forms of video under a single brand.\n\n\nFor Framework Technical Minute, I’m Mark Lassoff\n\nWeb:  http://www.frameworktv.com\nFacebook:  https://www.facebook.com/groups/frameworkcommunity/",
         "thumbnail":"https://i.vimeocdn.com/video/828249092_800x450.png",
         "releaseDate":"2019-11-04T10:01:15-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "coding"
         ],
         "content":{
            "dateAdded":"2019-11-08T12:17:49-05:00",
            "duration":63,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/370893009.hd.mp4?s=3ffa72cb96d73d7cdeeabdde8088011bdbe3d56a\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":3676610
               }
            ]
         }
      },
      {
         "id":"372716046",
         "title":"Augmented Reality Versus Virtual Reality | Framework Technical Report 006",
         "shortDescription":"Augmented Reality Versus Virtual Reality. Augmented Reality and Virtual Reality are two different technologies used to represent the real world with digital augmentation, and a completely virtual world.  In this video, Mark will explain the difference between augmented reality and virtual reality.\n\nTranscript\nFrom futurists to tech junkie— everyone seems to be talking about AR and VR technology. Known formally as Augmented reality and Virtual reality, AR and VR could have a huge impact on everything from education and training to video games to how wars are fought.  \n\nAugmented reality adds digital elements to a live view of the real world.  We see Augmented frequently used in conjunction with mapping technology. Google famously uses AR technology to translate signs in maps from language to language.  Pokemon Go was another application of Augmented Reality.\n\nVirtual Reality is a completely immersive experience that shuts out the real world.  It allows the user to be transported to a completely different world and requires the use of VR mask.  The growth of both AR and VR has been exponential and the applications will only get more realistic as processing speed and available bandwidth continue to grow.\n\n\nFor Framework Technical Report, I’m Mark Lassoff\n\n\nWeb Site: http://www.frameworktv.com\nFacebook: https://www.facebook.com/FrameworkTelevision",
         "thumbnail":"https://i.vimeocdn.com/video/830619366_800x450.png",
         "releaseDate":"2019-11-12T15:01:29-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "coding"
         ],
         "content":{
            "dateAdded":"2019-11-12T15:07:23-05:00",
            "duration":69,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/372716046.hd.mp4?s=694683ed3a4a4782812378b38fc58212725659f2\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":3854985
               }
            ]
         }
      },
      {
         "id":"371686698",
         "title":"Python Variables Expressions And Statements | The Framework Coding Show Ep 001",
         "shortDescription":"In this episode of the Framework Coding Show, host Mark Lasssoff covers Python variables, expressions, and Statements.  The Framework Coding show provides a short code lesson in each episode, helping you learn contemporary coding skills quickly and easily.\n\nThe Python programming language is an easy to learn, common but powerful programming language.  During the show, Mark will demonstrate the print() statement, how to use variables and expressions in Python.\n\nLinks from the show:\nDownload the show companion:  http://frameworktv.com/p/coding-show-...\nSite for writing Python:  http://repl.it/languages/python",
         "thumbnail":"https://i.vimeocdn.com/video/843659024_800x450.png",
         "releaseDate":"2019-11-07T12:28:29-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "coding"
         ],
         "content":{
            "dateAdded":"2019-11-08T12:17:49-05:00",
            "duration":1151,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/371686698.hd.mp4?s=e0faaeb34f7f624619c228414e7d9a1b1ae502a5\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1036157
               }
            ]
         }
      },
      {
         "id":"373641479",
         "title":"Python Conditional Statements | The Framework Coding Show Ep 002",
         "shortDescription":"In this episode of the Framework Coding Show, host Mark Lasssoff covers Python conditional statements.  The Framework Coding show provides a short code lesson in each episode, helping you learn contemporary coding skills quickly and easily.\n\nThe Python programming language is an easy to learn, common but powerful programming language.  During the show, Mark will demonstrate the print() statement, how to use variables and expressions in Python.\n\nLinks from the show:\nJoin Framework and Download the Show Companion:  http://www.frameworktv.com\nSite for writing Python:  http://repl.it/languages/python\n\n#Python",
         "thumbnail":"https://i.vimeocdn.com/video/843659563_800x450.png",
         "releaseDate":"2019-11-16T15:40:49-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "coding"
         ],
         "content":{
            "dateAdded":"2020-01-03T13:14:57-05:00",
            "duration":1057,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/373641479.hd.mp4?s=8355411233f9787717451aa11bbebecf49da7517\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1126664
               }
            ]
         }
      },
      {
         "id":"381901098",
         "title":"Lists and Tuples in Python | The Framework Coding Show Ep 003",
         "shortDescription":"In this episode of the Framework Coding Show, host Mark Lasssoff covers tuples and lists in Python.\n\nThe Framework Coding show provides a short code lesson in each episode, helping you learn contemporary coding skills quickly and easily.",
         "thumbnail":"https://i.vimeocdn.com/video/843659900_800x450.png",
         "releaseDate":"2019-12-29T11:46:20-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "coding"
         ],
         "content":{
            "dateAdded":"2020-01-03T13:14:57-05:00",
            "duration":698,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/381901098.hd.mp4?s=85342ecf6b13d18871c6d97c231f8db07e530a0c\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1314658
               }
            ]
         }
      },
      {
         "id":"381901224",
         "title":"Loops in Python | The Framework Coding Show Ep 004",
         "shortDescription":"In this episode of the Framework Coding Show, host Mark Lasssoff looks into loops in Python.\n\nThe Framework Coding show provides a short code lesson in each episode, helping you learn contemporary coding skills quickly and easily.",
         "thumbnail":"https://i.vimeocdn.com/video/843660957_800x450.png",
         "releaseDate":"2019-12-29T11:47:41-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "coding"
         ],
         "content":{
            "dateAdded":"2020-01-03T13:14:57-05:00",
            "duration":626,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/381901224.hd.mp4?s=dfba76128b6c1266a2be722c982fa04f30df0f5e\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1225358
               }
            ]
         }
      },
      {
         "id":"386978645",
         "title":"Framework Coding Show 005 - Vanilla JavaScript Project",
         "shortDescription":"Code along with Mark as he creates another complete application using Vanilla JavaScript.  \n\nVanilla JavaScript?  That's plain old JavaScript without frameworks or libraries.  Coding old school!  In this episode of Framework Coding Show, join Mark as he creates a full \"Civic Information Application\" that shows all of the US government representatives for any given address.\n\nThis app makes use of the Google Civic Information API, as well as the fetch() method to communicate with the API.",
         "thumbnail":"https://i.vimeocdn.com/video/849754770_800x450.png",
         "releaseDate":"2020-01-24T10:49:14-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "coding"
         ],
         "content":{
            "dateAdded":"2020-01-24T10:58:20-05:00",
            "duration":1484,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/386978645.hd.mp4?s=95ce8accca3bfed04443ac3b419ac11c3e883573\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1416530
               }
            ]
         }
      },
      {
         "id":"386974679",
         "title":"Roku HTML 5 Introduction",
         "shortDescription":"Watch this video before starting the HTML5 Certification for information on how to obtain the Certification.",
         "thumbnail":"https://i.vimeocdn.com/video/849750550_800x450.png",
         "releaseDate":"2020-01-24T10:32:18-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-24T10:35:37-05:00",
            "duration":82,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/386974679.hd.mp4?s=95fe0c5c2e695f8b18920266e1906798c3e561b3\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":3553985
               }
            ]
         }
      },
      {
         "id":"383177820",
         "title":"Basic Document Structure",
         "shortDescription":"Learn about the structure behind every web site and many mobile apps.  The basic document structure is the foundation of HTML.",
         "thumbnail":"https://i.vimeocdn.com/video/844691516_800x450.png",
         "releaseDate":"2020-01-06T18:43:45-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:34:45-05:00",
            "duration":439,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383177820.hd.mp4?s=cbf52e8a3be3f158074795a407e887e14c8b5868\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1422720
               }
            ]
         }
      },
      {
         "id":"383177852",
         "title":"Heading Tags",
         "shortDescription":"Learn how to use hierarchical heading tags in HTML documents.",
         "thumbnail":"https://i.vimeocdn.com/video/844692787_800x450.png",
         "releaseDate":"2020-01-06T18:43:57-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:34:45-05:00",
            "duration":276,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383177852.hd.mp4?s=0e10b712236daee683bbbfb25f12930c989ebfe7\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1563396
               }
            ]
         }
      },
      {
         "id":"383177858",
         "title":"Paragraph Tags",
         "shortDescription":"The paragraph tag is frequently used to markup up text content.",
         "thumbnail":"https://i.vimeocdn.com/video/844693079_800x450.png",
         "releaseDate":"2020-01-06T18:44:00-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:34:45-05:00",
            "duration":166,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383177858.hd.mp4?s=2092b69ccfdda916250f42b46d7e7a2fe968a07c\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1479817
               }
            ]
         }
      },
      {
         "id":"383177862",
         "title":"More HTML5 Tags",
         "shortDescription":"Learn about additional tags that are frequently used to mark up text content in HTML.",
         "thumbnail":"https://i.vimeocdn.com/video/844693241_800x450.png",
         "releaseDate":"2020-01-06T18:44:02-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:34:45-05:00",
            "duration":390,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383177862.hd.mp4?s=af95d6102bcf5670dd6f7e2dac9e3d0b612a2d08\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1638346
               }
            ]
         }
      },
      {
         "id":"383295743",
         "title":"Getting Started with CSS",
         "shortDescription":"Get started on the look and feel of your HTML5 content with CSS.",
         "thumbnail":"https://i.vimeocdn.com/video/844693586_800x450.png",
         "releaseDate":"2020-01-07T09:41:08-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:54:08-05:00",
            "duration":790,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383295743.hd.mp4?s=2102ad23d94651b6bfb5f4dd0e157f814ac34529\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1337097
               }
            ]
         }
      },
      {
         "id":"383177869",
         "title":"Div and Span Elements",
         "shortDescription":"Div and Span elements are used to create divisions within your content for styling.",
         "thumbnail":"https://i.vimeocdn.com/video/844693769_800x450.png",
         "releaseDate":"2020-01-06T18:44:06-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:34:45-05:00",
            "duration":555,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383177869.hd.mp4?s=9ab3691939b45d64aafdf15991ec0984a6efdba4\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1157407
               }
            ]
         }
      },
      {
         "id":"383177873",
         "title":"Google Fonts",
         "shortDescription":"Google fonts give you the ability to choose from hundreds and hundreds of available font options.",
         "thumbnail":"https://i.vimeocdn.com/video/844694500_800x450.png",
         "releaseDate":"2020-01-06T18:44:08-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:34:45-05:00",
            "duration":496,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383177873.hd.mp4?s=db7253e1878564f6d27cd989302a5166e45caf57\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1284212
               }
            ]
         }
      },
      {
         "id":"383177880",
         "title":"CSS Libraries",
         "shortDescription":"CSS Libraries can do the heavy lifting for you and allow you to automatically style a document.",
         "thumbnail":"https://i.vimeocdn.com/video/844694724_800x450.png",
         "releaseDate":"2020-01-06T18:44:11-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:34:45-05:00",
            "duration":301,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383177880.hd.mp4?s=234731466c0026b1d88fb31dc28f82693a8095de\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1449558
               }
            ]
         }
      },
      {
         "id":"383177885",
         "title":"Lists in HTML5",
         "shortDescription":"People tend to scan more than they read online. HTML lists provide a scannable option for displaying content.",
         "thumbnail":"https://i.vimeocdn.com/video/844694956_800x450.png",
         "releaseDate":"2020-01-06T18:44:13-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:34:45-05:00",
            "duration":346,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383177885.hd.mp4?s=07027a34c1fc1b945fa6f79761e2c387480642b7\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1029491
               }
            ]
         }
      },
      {
         "id":"383177893",
         "title":"HTML5 Hyperlinks",
         "shortDescription":"Links are what catalyzed the growth of the web. In this video, you'll learn to create hyperlinks between pages and sites.",
         "thumbnail":"https://i.vimeocdn.com/video/844695267_800x450.png",
         "releaseDate":"2020-01-06T18:44:16-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:34:45-05:00",
            "duration":592,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383177893.hd.mp4?s=d6ead0646fdf068e4cf980749863512233f9bb7a\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1225041
               }
            ]
         }
      },
      {
         "id":"383296450",
         "title":"HTML5 Tables",
         "shortDescription":"Learn how to create tables with HTML and style them with CSS.",
         "thumbnail":"https://i.vimeocdn.com/video/844695915_800x450.png",
         "releaseDate":"2020-01-07T09:44:20-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:54:08-05:00",
            "duration":932,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383296450.hd.mp4?s=833cb84250c48c1e651f6ccc54381765e7a4e32e\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1213703
               }
            ]
         }
      },
      {
         "id":"383296041",
         "title":"HTML5 Media",
         "shortDescription":"Learn how to display images, video and stream audio with HTML.",
         "thumbnail":"https://i.vimeocdn.com/video/844695672_800x450.png",
         "releaseDate":"2020-01-07T09:42:41-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:54:08-05:00",
            "duration":680,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383296041.hd.mp4?s=249feb7127e3463cc4c73132a2e08f328b6fcb0a\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1602428
               }
            ]
         }
      },
      {
         "id":"383177909",
         "title":"HTML5 Forms",
         "shortDescription":"Forms are important because they are the element that your users will interact with most. Learn to create forms in this section.",
         "thumbnail":"https://i.vimeocdn.com/video/844696408_800x450.png",
         "releaseDate":"2020-01-06T18:44:21-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:34:45-05:00",
            "duration":1088,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383177909.hd.mp4?s=8456795ab789e63b120d3e3228a7f99ebac224f5\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1370580
               }
            ]
         }
      },
      {
         "id":"383177833",
         "title":"HTML5 Buttons",
         "shortDescription":"Learn to create buttons in HTML.",
         "thumbnail":"https://i.vimeocdn.com/video/844696855_800x450.png",
         "releaseDate":"2020-01-06T18:43:50-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:34:45-05:00",
            "duration":464,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383177833.hd.mp4?s=9923c810d2ccb4e896c109c1dede225586aa41ee\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1131730
               }
            ]
         }
      },
      {
         "id":"383177844",
         "title":"The CSS Box Model",
         "shortDescription":"The box model is the basis for all web page layout.  Mark explains in this video.",
         "thumbnail":"https://i.vimeocdn.com/video/844697120_800x450.png",
         "releaseDate":"2020-01-06T18:43:53-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:34:45-05:00",
            "duration":555,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383177844.hd.mp4?s=3982a7ebebbc79191e37f31808e63b69588e4243\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1115082
               }
            ]
         }
      },
      {
         "id":"383177847",
         "title":"CSS Page Layout",
         "shortDescription":"Learn the traditional method of laying out pages with HTML5 and CSS.",
         "thumbnail":"https://i.vimeocdn.com/video/844697416_800x450.png",
         "releaseDate":"2020-01-06T18:43:55-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T09:34:45-05:00",
            "duration":891,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383177847.hd.mp4?s=814a6360b34b8923214b1a5a3cc507b2431cdf89\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1875467
               }
            ]
         }
      },
      {
         "id":"383303721",
         "title":"Page Layout with Flexbox",
         "shortDescription":"Learn the new Flexbox method of page layout.",
         "thumbnail":"https://i.vimeocdn.com/video/844697926_800x450.png",
         "releaseDate":"2020-01-07T10:21:25-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "HTML",
            "technology"
         ],
         "content":{
            "dateAdded":"2020-01-07T10:23:30-05:00",
            "duration":789,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/383303721.hd.mp4?s=0d2defc2d847267861ae9de4606eb8f53bcbc692\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1668184
               }
            ]
         }
      },
      {
         "id":"390579876",
         "title":"How to Begin Coding | 7 Tips to Start Coding Today",
         "shortDescription":"Are you wondering how to begin coding? Do you want to learn to program but haven't found the right place to start? In this video, join Framework's Mark Lassoff as he reviews 7 Tips to help you Begin Coding today. Mark will discuss how to get started if you want to learn to code and provide invaluable tips that will get you moving down the right path.\n",
         "thumbnail":"https://i.vimeocdn.com/video/854762745_800x450.png",
         "releaseDate":"2020-02-10T15:11:14-05:00\n",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "coding"
         ],
         "content":{
            "dateAdded":"2020-02-10T15:18:52-05:00",
            "duration":353,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/390579876.hd.mp4?s=15657e0b9e412709f2dc8f968761cec7f8a8aa30\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":4039124
               }
            ]
         }
      },
      {
         "id":"390579886",
         "title":"Learn JavaScript in 1 Hour",
         "shortDescription":"JavaScript might be the most important language you can learn right now. If you can learn JavaScript in 1 Hour, why not get started? This JavaScript programming course covers all the basics that you need to know to start coding in the JavaScript programming language. You are encouraged to code along with the instructor in order to learn step-by-step.",
         "thumbnail":"https://i.vimeocdn.com/video/854763448_800x450.png",
         "releaseDate":"2020-02-10T15:11:15-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "new",
             "coding"
         ],
         "content":{
            "dateAdded":"2020-02-10T15:21:12-05:00",
            "duration":3801,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/390579886.hd.mp4?s=36542fa17ce48c836a3542cc2db680b02d9586b9\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":803343
               }
            ]
         }
      },
      {
         "id":"390589091",
         "title":"Build an App From Scratch",
         "shortDescription":"Join Mark Lassoff and Framework Television to Build an App From Scratch with JavaScript. In this video, Mark will create four versions of the application so you can see how core functionality is coded and additional features are added in new iterations. You'll see exactly how to build an app from start to finish as JavaScript and jQuery are used to create the project. The app itself is a random password generator, which allows you to create a password of any reasonable length and choose the types of characters that are included in the application. As the process of building an app continues, features are added to make the password generator more useful.",
         "thumbnail":"https://i.vimeocdn.com/video/854774466_800x450.png",
         "releaseDate":"2020-02-10T15:53:29-05:00",
         "genres":[
            "educational",
            "technology"
         ],
         "tags":[
            "new",
            "coding",
             "coding_projects"
         ],
         "content":{
            "dateAdded":"2020-02-10T15:55:00-05:00",
            "duration":2369,
            "videos":[
               {
                  "url":"https://player.vimeo.com/external/390589091.hd.mp4?s=cb13096ac14f5a70f6f83d605fd580971f80d78a\u0026profile_id=175",
                  "quality":"FHD",
                  "videoType":"MP4",
                  "bitrate":1026472
               }
            ]
         }
      }
   ]
}